version: "3"
services:
  gdatastore:
    build: ./datastore/
    ports:
     - "8081:8081"
  mongodb:
    image: mongo:3.6.0-jessie
    ports:
     - "27017:27017"
  web:
      build: ./malleus/
      volumes:
       - .:/src
      command: >
        /bin/bash -c "
          while ! nc -z gdatastore 8081;
          do
            echo sleeping;
            sleep 1;
          done;
          echo Connected!;
          pytest /src/malleus/tests;
        "
      depends_on:
        - gdatastore
        - mongodb
      ports:
       - "8000:8000"
      environment:
       - DATASTORE_PROJECT_ID=malleus-local
       - DATASTORE_DATASET=malleus-local
       - DATASTORE_EMULATOR_HOST=gdatastore:8081
       - DATASTORE_EMULATOR_HOST_PATH=gdatastore:8081/datastore
       - DATASTORE_HOST=gdatastore:8081
       - MONGODB_HOST=mongodb:27017
