#!/usr/bin/env python3

import argparse
import subprocess, os

parser = argparse.ArgumentParser()
subparsers = parser.add_subparsers()

parser.add_argument("--test", required=False, action='store_true')
parser.add_argument("--run", required=False, action='store_true')

parser.add_argument("--local", required=False, action='store_true')
parser.add_argument("--docker", required=False, action='store_true')

args, leftovers = parser.parse_known_args()

is_docker = args.docker
is_local = args.local

is_run = args.run
is_test = args.test

is_prod = not(is_docker or is_local)

if (is_docker and is_local):
    print("Must select ONE of local or docker, but not both")
    exit(1)

if (is_run and is_test):
    print("Must select ONE of run or test, but not both")
    exit(1)
    
env = os.environ.copy()

env["DATASTORE_DATASET"] = "malleus-local"
env["DATASTORE_EMULATOR_HOST"] = "localhost:8081"
env["DATASTORE_EMULATOR_HOST_PATH"] = "localhost:8081/datastore"
env["DATASTORE_HOST"] = "http://localhost:8081"
env["DATASTORE_PROJECT_ID"] = "malleus-local"

if is_test:
    if is_local:
        subprocess.Popen(["pytest", "api/tests"],env=env)
    if is_docker:
        # TODO: What if docker image is not built?
        cmd = """
        docker run -e DATASTORE_EMULATOR_HOST='docker.for.mac.localhost:8081' \
           -e DATASTORE_PROJECT_ID='malleus-local' \
           -e DATASTORE_DATASET='malleus-local' \
           -e DATASTORE_EMULATOR_HOST='docker.for.mac.localhost:8081' \
           -e DATASTORE_EMULATOR_HOST_PATH='docker.for.mac.localhost:8081/datastore' \
           -e DATASTORE_HOST='http://docker.for.mac.localhost:8081' \
           -v """ + os.getcwd() + """/api:/src malleus-api pytest tests """
        subprocess.Popen(cmd.split()).wait() #TODO: Does ctrl-c kill this process?
