#!/bin/bash
set -x

export DATASTORE_DATASET=malleus-local
export DATASTORE_EMULATOR_HOST=localhost:8081
export DATASTORE_EMULATOR_HOST_PATH=localhost:8081/datastore
export DATASTORE_HOST=http://localhost:8081
export DATASTORE_PROJECT_ID=malleus-local

pytest api/tests