# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: malleus/api/domain/protos/timings.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from malleus.api.domain.protos import timing_pb2 as malleus_dot_api_dot_domain_dot_protos_dot_timing__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='malleus/api/domain/protos/timings.proto',
  package='malleus.api.domain',
  syntax='proto3',
  serialized_pb=_b('\n\'malleus/api/domain/protos/timings.proto\x12\x12malleus.api.domain\x1a&malleus/api/domain/protos/timing.proto\"6\n\x07Timings\x12+\n\x07timings\x18\x01 \x03(\x0b\x32\x1a.malleus.api.domain.Timingb\x06proto3')
  ,
  dependencies=[malleus_dot_api_dot_domain_dot_protos_dot_timing__pb2.DESCRIPTOR,])




_TIMINGS = _descriptor.Descriptor(
  name='Timings',
  full_name='malleus.api.domain.Timings',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='timings', full_name='malleus.api.domain.Timings.timings', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=103,
  serialized_end=157,
)

_TIMINGS.fields_by_name['timings'].message_type = malleus_dot_api_dot_domain_dot_protos_dot_timing__pb2._TIMING
DESCRIPTOR.message_types_by_name['Timings'] = _TIMINGS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Timings = _reflection.GeneratedProtocolMessageType('Timings', (_message.Message,), dict(
  DESCRIPTOR = _TIMINGS,
  __module__ = 'malleus.api.domain.protos.timings_pb2'
  # @@protoc_insertion_point(class_scope:malleus.api.domain.Timings)
  ))
_sym_db.RegisterMessage(Timings)


# @@protoc_insertion_point(module_scope)
